version: "3"

volumes:
  config:
    driver: local
  dnsmasq:
    driver: local

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      - ADMIN_EMAIL
      - TZ=Europe/Amsterdam
      - WEBPASSWORD
      - DNS1=127.0.0.1
      - DNS2=1.1.1.1
      - DNS_BOGUS_PRIV=true
      - DNS_FQDN_REQUIRED=true
      - REV_SERVER=true
      - REV_SERVER_DOMAIN
      - REV_SERVER_TARGET
      - REV_SERVER_CIDR
      - ServerIP
      - VIRTUAL_HOST
      - IPv6=false
      - DNSMASQ_LISTENING=all
      - DNSMASQ_USER=pihole
      - TEMPERATUREUNIT=c
      - WEBUIBOXEDLAYOUT=traditional
      - SKIPGRAVITYONBOOT=1
    volumes:
      - 'config:/etc/pihole/'
      - 'dnsmasq:/etc/dnsmasq.d/'
    restart: unless-stopped
